#!/usr/bin/env python3
"""One-shot patch: add small breadbasket feeder ports, farms, lanes, npc_lanes,
institutional_trade.phase3 bands, port_cultures, port_shipyards to data/world_full.json.

Run from repo root:  python3 tools/apply_feeding_colonies.py
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORLD = ROOT / "data" / "world_full.json"

# (port dict, farm grain/wine/fish, [(from, to, days_int), ...], [(from, to, days_float), ...])
PATCH = [
    # Corinth orbit (aegean)
    (
        {
            "id": "cenchreae_bread",
            "name": "Cenchreae (grain road)",
            "map_u": 0.586,
            "map_v": 0.524,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 140,
                "wine": 55,
                "salt": 28,
                "olive_oil": 40,
                "pottery": 40,
                "fish": 35,
                "timber": 22,
                "textiles": 22,
                "metal": 12,
                "wire": 9,
                "spice": 4,
                "slaves": 22,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 3,
            "initial_wealth": 108,
            "trade_price_bias": {"grain": -0.07, "wine": -0.04},
            "npc_traders_base": 3,
            "chart_area_id": "aegean",
        },
        (12, 3, 3),
        [("cenchreae_bread", "corinth", 1)],
        [("cenchreae_bread", "corinth", 1.0, "coastal")],
    ),
    (
        {
            "id": "sicyon_bread",
            "name": "Sicyon (coastal fields)",
            "map_u": 0.552,
            "map_v": 0.531,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 135,
                "wine": 52,
                "salt": 26,
                "olive_oil": 38,
                "pottery": 38,
                "fish": 32,
                "timber": 20,
                "textiles": 20,
                "metal": 11,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 3,
            "initial_wealth": 105,
            "trade_price_bias": {"grain": -0.07},
            "npc_traders_base": 3,
            "chart_area_id": "aegean",
        },
        (11, 3, 3),
        [("sicyon_bread", "corinth", 1)],
        [("sicyon_bread", "corinth", 1.0, "coastal")],
    ),
    (
        {
            "id": "troezen_coast",
            "name": "Troezen (Argolid grain)",
            "map_u": 0.545,
            "map_v": 0.518,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 130,
                "wine": 50,
                "salt": 25,
                "olive_oil": 36,
                "pottery": 36,
                "fish": 34,
                "timber": 20,
                "textiles": 20,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 4,
            "initial_wealth": 102,
            "trade_price_bias": {"grain": -0.06, "fish": -0.04},
            "npc_traders_base": 3,
            "chart_area_id": "aegean",
        },
        (11, 3, 4),
        [("troezen_coast", "corinth", 2)],
        [("troezen_coast", "corinth", 2.0, "coastal")],
    ),
    # Massalia orbit
    (
        {
            "id": "agde_bread",
            "name": "Agde (coastal granary)",
            "map_u": 0.218,
            "map_v": 0.165,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 138,
                "wine": 54,
                "salt": 30,
                "olive_oil": 40,
                "pottery": 40,
                "fish": 38,
                "timber": 22,
                "textiles": 22,
                "metal": 11,
                "wire": 8,
                "spice": 4,
                "slaves": 22,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 3,
            "initial_wealth": 106,
            "trade_price_bias": {"grain": -0.07},
            "npc_traders_base": 3,
            "chart_area_id": "iberia_gaul",
        },
        (12, 3, 3),
        [("agde_bread", "massalia", 2)],
        [("agde_bread", "massalia", 2.0, "coastal")],
    ),
    (
        {
            "id": "ager_narbonensis",
            "name": "Narbonensis strip (grain)",
            "map_u": 0.188,
            "map_v": 0.195,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 142,
                "wine": 52,
                "salt": 28,
                "olive_oil": 38,
                "pottery": 38,
                "fish": 36,
                "timber": 22,
                "textiles": 22,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 3,
            "initial_wealth": 104,
            "trade_price_bias": {"grain": -0.07},
            "npc_traders_base": 3,
            "chart_area_id": "iberia_gaul",
        },
        (12, 3, 3),
        [("ager_narbonensis", "massalia", 2)],
        [("ager_narbonensis", "massalia", 2.0, "coastal")],
    ),
    (
        {
            "id": "arelate_bread",
            "name": "Arelate (Rhône delta grain)",
            "map_u": 0.232,
            "map_v": 0.178,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 145,
                "wine": 50,
                "salt": 27,
                "olive_oil": 36,
                "pottery": 36,
                "fish": 34,
                "timber": 22,
                "textiles": 22,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 3,
            "initial_wealth": 105,
            "trade_price_bias": {"grain": -0.08},
            "npc_traders_base": 3,
            "chart_area_id": "iberia_gaul",
        },
        (13, 3, 3),
        [("arelate_bread", "massalia", 2)],
        [("arelate_bread", "massalia", 2.0, "coastal")],
    ),
    # Kition orbit
    (
        {
            "id": "larnaca_fields",
            "name": "Larnaca plain (grain)",
            "map_u": 0.852,
            "map_v": 0.642,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 132,
                "wine": 48,
                "salt": 32,
                "olive_oil": 34,
                "pottery": 34,
                "fish": 40,
                "timber": 20,
                "textiles": 20,
                "metal": 10,
                "wire": 8,
                "spice": 4,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 4,
            "initial_wealth": 102,
            "trade_price_bias": {"grain": -0.07, "fish": -0.04},
            "npc_traders_base": 3,
            "chart_area_id": "levant_cyprus",
        },
        (12, 3, 4),
        [("larnaca_fields", "kition", 1)],
        [("larnaca_fields", "kition", 1.0, "coastal")],
    ),
    (
        {
            "id": "kourion_coast",
            "name": "Kourion (coastal barley)",
            "map_u": 0.828,
            "map_v": 0.652,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 128,
                "wine": 46,
                "salt": 30,
                "olive_oil": 32,
                "pottery": 32,
                "fish": 42,
                "timber": 20,
                "textiles": 20,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 4,
            "initial_wealth": 100,
            "trade_price_bias": {"grain": -0.06},
            "npc_traders_base": 3,
            "chart_area_id": "levant_cyprus",
        },
        (11, 3, 4),
        [("kourion_coast", "kition", 1)],
        [("kourion_coast", "kition", 1.0, "coastal")],
    ),
    (
        {
            "id": "maroni_plain",
            "name": "Maroni (eastern Cyprus grain)",
            "map_u": 0.862,
            "map_v": 0.658,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 125,
                "wine": 44,
                "salt": 30,
                "olive_oil": 32,
                "pottery": 32,
                "fish": 38,
                "timber": 20,
                "textiles": 20,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 3,
            "initial_wealth": 98,
            "trade_price_bias": {"grain": -0.06},
            "npc_traders_base": 3,
            "chart_area_id": "levant_cyprus",
        },
        (11, 3, 3),
        [("maroni_plain", "kition", 1), ("maroni_plain", "salamis_cyprus", 1)],
        [
            ("maroni_plain", "kition", 1.0, "coastal"),
            ("maroni_plain", "salamis_cyprus", 1.0, "coastal"),
        ],
    ),
    # Selinus orbit
    (
        {
            "id": "mazara_bread",
            "name": "Mazara (Sicilian grain)",
            "map_u": 0.298,
            "map_v": 0.578,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 138,
                "wine": 52,
                "salt": 26,
                "olive_oil": 38,
                "pottery": 38,
                "fish": 36,
                "timber": 22,
                "textiles": 22,
                "metal": 11,
                "wire": 8,
                "spice": 3,
                "slaves": 22,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 3,
            "initial_wealth": 104,
            "trade_price_bias": {"grain": -0.07},
            "npc_traders_base": 3,
            "chart_area_id": "sicily_ionian",
        },
        (12, 3, 3),
        [("mazara_bread", "selinus", 1)],
        [("mazara_bread", "selinus", 1.0, "coastal")],
    ),
    (
        {
            "id": "sciacca_coast",
            "name": "Sciacca roadstead (grain)",
            "map_u": 0.318,
            "map_v": 0.592,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 134,
                "wine": 50,
                "salt": 26,
                "olive_oil": 36,
                "pottery": 36,
                "fish": 38,
                "timber": 22,
                "textiles": 22,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 4,
            "initial_wealth": 102,
            "trade_price_bias": {"grain": -0.06, "fish": -0.04},
            "npc_traders_base": 3,
            "chart_area_id": "sicily_ionian",
        },
        (11, 3, 4),
        [("sciacca_coast", "selinus", 1)],
        [("sciacca_coast", "selinus", 1.0, "coastal")],
    ),
    (
        {
            "id": "licata_bread",
            "name": "Licata (southern Sicily grain)",
            "map_u": 0.308,
            "map_v": 0.565,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 136,
                "wine": 48,
                "salt": 26,
                "olive_oil": 36,
                "pottery": 36,
                "fish": 34,
                "timber": 22,
                "textiles": 22,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 3,
            "initial_wealth": 101,
            "trade_price_bias": {"grain": -0.07},
            "npc_traders_base": 3,
            "chart_area_id": "sicily_ionian",
        },
        (12, 3, 3),
        [("licata_bread", "selinus", 1), ("licata_bread", "gela", 1)],
        [
            ("licata_bread", "selinus", 1.0, "coastal"),
            ("licata_bread", "gela", 1.0, "coastal"),
        ],
    ),
    # Rome / Ostia orbit
    (
        {
            "id": "tiber_mouth_bread",
            "name": "Tiber mouth farms",
            "map_u": 0.428,
            "map_v": 0.258,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 140,
                "wine": 48,
                "salt": 28,
                "olive_oil": 36,
                "pottery": 38,
                "fish": 30,
                "timber": 22,
                "textiles": 22,
                "metal": 11,
                "wire": 8,
                "spice": 3,
                "slaves": 22,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 2,
            "initial_wealth": 106,
            "trade_price_bias": {"grain": -0.07},
            "npc_traders_base": 3,
            "chart_area_id": "tyrrhenian",
        },
        (12, 3, 2),
        [("tiber_mouth_bread", "ostia", 1), ("tiber_mouth_bread", "rome", 2)],
        [
            ("tiber_mouth_bread", "ostia", 1.0, "coastal"),
            ("tiber_mouth_bread", "rome", 1.5, "coastal"),
        ],
    ),
    (
        {
            "id": "velletri_plain",
            "name": "Velletri plain (Latium grain)",
            "map_u": 0.322,
            "map_v": 0.338,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 132,
                "wine": 46,
                "salt": 26,
                "olive_oil": 34,
                "pottery": 36,
                "fish": 28,
                "timber": 22,
                "textiles": 22,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 2,
            "initial_wealth": 102,
            "trade_price_bias": {"grain": -0.06},
            "npc_traders_base": 3,
            "chart_area_id": "tyrrhenian",
        },
        (11, 3, 2),
        [("velletri_plain", "rome", 1)],
        [("velletri_plain", "rome", 1.0, "coastal")],
    ),
    (
        {
            "id": "antium_coast",
            "name": "Antium coast (grain)",
            "map_u": 0.358,
            "map_v": 0.272,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 128,
                "wine": 44,
                "salt": 28,
                "olive_oil": 34,
                "pottery": 36,
                "fish": 32,
                "timber": 22,
                "textiles": 22,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 3,
            "initial_wealth": 100,
            "trade_price_bias": {"grain": -0.06, "fish": -0.04},
            "npc_traders_base": 3,
            "chart_area_id": "tyrrhenian",
        },
        (11, 3, 3),
        [("antium_coast", "ostia", 2)],
        [("antium_coast", "ostia", 1.5, "coastal")],
    ),
    # Carthage orbit
    (
        {
            "id": "thapsus_bread",
            "name": "Thapsus strip (grain)",
            "map_u": 0.362,
            "map_v": 0.598,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 136,
                "wine": 48,
                "salt": 34,
                "olive_oil": 32,
                "pottery": 32,
                "fish": 36,
                "timber": 20,
                "textiles": 20,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 22,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 4,
            "initial_wealth": 103,
            "trade_price_bias": {"grain": -0.07},
            "npc_traders_base": 3,
            "chart_area_id": "north_africa",
        },
        (12, 3, 4),
        [("thapsus_bread", "carthage", 2)],
        [("thapsus_bread", "carthage", 2.0, "coastal")],
    ),
    (
        {
            "id": "lepcis_minor_bread",
            "name": "Leptis Minor (Sahel grain)",
            "map_u": 0.398,
            "map_v": 0.552,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 130,
                "wine": 44,
                "salt": 36,
                "olive_oil": 30,
                "pottery": 30,
                "fish": 34,
                "timber": 20,
                "textiles": 20,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 4,
            "initial_wealth": 99,
            "trade_price_bias": {"grain": -0.06},
            "npc_traders_base": 3,
            "chart_area_id": "north_africa",
        },
        (11, 3, 4),
        [("lepcis_minor_bread", "carthage", 3)],
        [("lepcis_minor_bread", "carthage", 2.5, "coastal")],
    ),
    (
        {
            "id": "pupput_fields",
            "name": "Pupput (Cap Bon grain)",
            "map_u": 0.384,
            "map_v": 0.562,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 134,
                "wine": 46,
                "salt": 32,
                "olive_oil": 32,
                "pottery": 32,
                "fish": 38,
                "timber": 20,
                "textiles": 20,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 4,
            "initial_wealth": 101,
            "trade_price_bias": {"grain": -0.07, "fish": -0.04},
            "npc_traders_base": 3,
            "chart_area_id": "north_africa",
        },
        (12, 3, 4),
        [("pupput_fields", "carthage", 1)],
        [("pupput_fields", "carthage", 1.0, "coastal")],
    ),
    # Gades orbit
    (
        {
            "id": "baitis_estuary",
            "name": "Baetis estuary farms",
            "map_u": 0.018,
            "map_v": 0.718,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 140,
                "wine": 50,
                "salt": 40,
                "olive_oil": 34,
                "pottery": 34,
                "fish": 42,
                "timber": 22,
                "textiles": 22,
                "metal": 12,
                "wire": 9,
                "spice": 4,
                "slaves": 22,
                "gold": 0,
                "silver": 2,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 4,
            "initial_wealth": 104,
            "trade_price_bias": {"grain": -0.07, "fish": -0.05},
            "npc_traders_base": 3,
            "chart_area_id": "iberia_gaul",
        },
        (12, 3, 4),
        [("baitis_estuary", "gades", 1)],
        [("baitis_estuary", "gades", 1.0, "coastal")],
    ),
    (
        {
            "id": "onoba_bread",
            "name": "Onoba (Atlantic grain)",
            "map_u": 0.042,
            "map_v": 0.698,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 132,
                "wine": 48,
                "salt": 38,
                "olive_oil": 32,
                "pottery": 32,
                "fish": 44,
                "timber": 22,
                "textiles": 22,
                "metal": 11,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 5,
            "initial_wealth": 100,
            "trade_price_bias": {"grain": -0.06, "fish": -0.05},
            "npc_traders_base": 3,
            "chart_area_id": "iberia_gaul",
        },
        (11, 3, 5),
        [("onoba_bread", "gades", 1)],
        [("onoba_bread", "gades", 1.0, "coastal")],
    ),
    (
        {
            "id": "carteia_coast",
            "name": "Carteia (Bay of Cádiz grain)",
            "map_u": 0.032,
            "map_v": 0.728,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 128,
                "wine": 46,
                "salt": 40,
                "olive_oil": 30,
                "pottery": 30,
                "fish": 40,
                "timber": 20,
                "textiles": 20,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 4,
            "initial_wealth": 98,
            "trade_price_bias": {"grain": -0.06, "fish": -0.05},
            "npc_traders_base": 3,
            "chart_area_id": "iberia_gaul",
        },
        (11, 3, 4),
        [("carteia_coast", "gades", 1)],
        [("carteia_coast", "gades", 1.0, "coastal")],
    ),
    # Tyre orbit
    (
        {
            "id": "acre_feed",
            "name": "Acre plain (grain)",
            "map_u": 0.882,
            "map_v": 0.642,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 130,
                "wine": 46,
                "salt": 38,
                "olive_oil": 32,
                "pottery": 32,
                "fish": 38,
                "timber": 20,
                "textiles": 20,
                "metal": 10,
                "wire": 8,
                "spice": 4,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 3,
            "initial_wealth": 100,
            "trade_price_bias": {"grain": -0.07},
            "npc_traders_base": 3,
            "chart_area_id": "levant_cyprus",
        },
        (11, 3, 3),
        [("acre_feed", "tyre", 1)],
        [("acre_feed", "tyre", 1.0, "coastal")],
    ),
    (
        {
            "id": "dor_coast_bread",
            "name": "Dor coast (grain)",
            "map_u": 0.898,
            "map_v": 0.658,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 126,
                "wine": 44,
                "salt": 36,
                "olive_oil": 30,
                "pottery": 30,
                "fish": 40,
                "timber": 20,
                "textiles": 20,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 4,
            "initial_wealth": 98,
            "trade_price_bias": {"grain": -0.06, "fish": -0.04},
            "npc_traders_base": 3,
            "chart_area_id": "levant_cyprus",
        },
        (11, 3, 4),
        [("dor_coast_bread", "tyre", 1)],
        [("dor_coast_bread", "tyre", 1.0, "coastal")],
    ),
    (
        {
            "id": "ptolemais_akkaron",
            "name": "Ptolemais (Akko plain grain)",
            "map_u": 0.902,
            "map_v": 0.632,
            "role": "breadbasket",
            "industrial_metal_per_day": 1,
            "industrial_wire_per_day": 1,
            "industrial_timber_per_day": 1,
            "industrial_textiles_per_day": 1,
            "initial_stock": {
                "grain": 128,
                "wine": 44,
                "salt": 36,
                "olive_oil": 30,
                "pottery": 30,
                "fish": 36,
                "timber": 20,
                "textiles": 20,
                "metal": 10,
                "wire": 8,
                "spice": 3,
                "slaves": 20,
                "gold": 0,
                "silver": 1,
            },
            "npc_traders": 20,
            "population_grain_per_day": 4,
            "population_wine_per_day": 2,
            "population_fish_per_day": 3,
            "initial_wealth": 99,
            "trade_price_bias": {"grain": -0.06},
            "npc_traders_base": 3,
            "chart_area_id": "levant_cyprus",
        },
        (11, 3, 3),
        [("ptolemais_akkaron", "tyre", 2), ("ptolemais_akkaron", "sidon", 1)],
        [
            ("ptolemais_akkaron", "tyre", 1.5, "coastal"),
            ("ptolemais_akkaron", "sidon", 1.0, "coastal"),
        ],
    ),
]


def _shipyard_for(chart: str, culture: str) -> list[str]:
    if chart == "iberia_gaul":
        return ["greek_merchant", "phoenician_deep"]
    if chart == "north_africa":
        return ["phoenician_deep", "levantine_luxury"]
    if chart == "levant_cyprus":
        return ["phoenician_deep", "levantine_luxury", "greek_merchant"]
    if chart == "sicily_ionian":
        return ["greek_merchant", "sicilian_grain"]
    if chart == "tyrrhenian":
        return ["italic_coastal", "greek_merchant"]
    return ["greek_merchant"]


def main() -> None:
    data = json.loads(WORLD.read_text())
    ports: list = data["ports"]
    farms: list = data["farms"]
    lanes: list = data["lanes"]
    npc_lanes: list = data["npc_lanes"]

    existing = {p["id"] for p in ports}
    if any(row[0]["id"] in existing for row in PATCH):
        print("Feeding colonies already present; skipping.")
        return
    for row in PATCH:
        pid = row[0]["id"]
        if pid in existing:
            raise SystemExit(f"port already exists: {pid}")
        existing.add(pid)

    for port, farm_rates, lane_pairs, npc_pairs in PATCH:
        ports.append(port)
        g, w, f = farm_rates
        farms.append(
            {
                "id": f"{port['id']}_hinterland",
                "name": f"{port['name']} hinterland",
                "port_id": port["id"],
                "grain_per_day": g,
                "wine_per_day": w,
                "fish_per_day": f,
            }
        )
        for a, b, days in lane_pairs:
            lanes.append({"from": a, "to": b, "days": int(days)})
        for a, b, days, tt in npc_pairs:
            npc_lanes.append({"from": a, "to": b, "days": float(days), "travel_type": tt})

    it = data.setdefault("institutional_trade", {})
    p3 = it.setdefault("phase3", {})
    bands = p3.setdefault("bands", [])
    # Replace / extend first two bands; append Iberia and Levant feeder bands.
    new_bands = [
        [
            "ostia",
            "neapolis",
            "rhegium",
            "messana",
            "panormus",
            "tiber_mouth_bread",
            "velletri_plain",
            "antium_coast",
        ],
        [
            "carthage",
            "hippo",
            "tingis",
            "thapsus_bread",
            "lepcis_minor_bread",
            "pupput_fields",
        ],
        [
            "gades",
            "malaka",
            "tingis",
            "baitis_estuary",
            "onoba_bread",
            "carteia_coast",
        ],
        [
            "tyre",
            "sidon",
            "acre_feed",
            "dor_coast_bread",
            "ptolemais_akkaron",
            "kition",
            "salamis_cyprus",
        ],
    ]
    p3["bands"] = new_bands

    pc = data.setdefault("port_cultures", {})
    ps = data.setdefault("port_shipyards", {})
    for port, _, _, _ in PATCH:
        pid = port["id"]
        chart = port["chart_area_id"]
        if chart == "aegean":
            cult = "greek"
        elif chart == "iberia_gaul":
            cult = "greek"
        elif chart == "levant_cyprus":
            cult = "phoenician"
        elif chart == "sicily_ionian":
            cult = "greek"
        elif chart == "tyrrhenian":
            cult = "italic"
        elif chart == "north_africa":
            cult = "phoenician"
        else:
            cult = "greek"
        pc[pid] = cult
        ps[pid] = _shipyard_for(chart, cult)

    # Refresh networked_node_map counts from npc_lanes (minimal: rebuild adjacency dict)
    nm = data.setdefault("networked_node_map", {})
    adj: dict[str, list] = defaultdict(list)
    for e in npc_lanes:
        a, b = str(e["from"]), str(e["to"])
        d = float(e["days"])
        tt = str(e.get("travel_type", "coastal"))
        adj[a].append({"to": b, "days": d, "travel_type": tt})
    nm["adjacency"] = dict(sorted(adj.items()))
    nm["node_count"] = len({p["id"] for p in ports})
    nm["directed_edge_count"] = len(npc_lanes)

    WORLD.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    print(f"Wrote {WORLD} with {len(PATCH)} new ports; total ports {len(ports)}.")


if __name__ == "__main__":
    main()
